CREATE DATABASE IF NOT EXISTS $(SQL_DATABASE);
CREATE USER IF NOT EXISTS '$(MYSQL_USER)'@'%' IDENTIFIED BY '$(MYSQL_PASSWORD)';
GRANT ALL PRIVILEGES ON $(SQL_DATABASE).* TO '$(MYSQL_USER)'@'%';
FLUSH PRIVILEGES;
